# Pod holding a container for use with the saints-xctf-kubernetes-test Jenkins job.
# Author: Andrew Jarombek
# Date: 2/21/2021

apiVersion: v1
kind: Pod
metadata:
  name: saints-xctf-kubernetes-test
  namespace: jenkins
  labels:
    version: v1.0.0
    environment: all
    application: saints-xctf-kubernetes-test
spec:
  containers:
    - name: go
      image: golang:1.14.4-buster
      tty: true
  serviceAccountName: jenkins-kubernetes-test
  automountServiceAccountToken: true
