# Pod holding multiple containers for use with the jarombek-com-test Jenkins job.
# Author: Andrew Jarombek
# Date: 6/27/2020

apiVersion: v1
kind: Pod
metadata:
  name: jarombek-com-test
  namespace: jenkins
  labels:
    version: v1.0.0
    environment: development
    application: jarombek-com-test
spec:
  containers:
    - name: test
      image: node:8-alpine
      tty: true
    - name: app
      image: ajarombek/jarombek-com
      tty: true
    - name: database
      image: ajarombek/jarombek-com-database
      tty: true


