# Pod holding a container for use with the jarombek-com-kubernetes-infrastructure-test Jenkins job.
# Author: Andrew Jarombek
# Date: 4/11/2021

apiVersion: v1
kind: Pod
metadata:
  name: jarombek-com-kubernetes-infrastructure-test
  namespace: jenkins
  labels:
    version: v1.0.0
    environment: development
    application: jarombek-com-kubernetes-infrastructure-test
spec:
  containers:
    - name: go
      image: golang:1.14.4-buster
      tty: true
  serviceAccountName: jenkins-kubernetes-test
  automountServiceAccountToken: true
