# Kubernetes Pods for end to end testing the SaintsXCTF Web application.
# Author: Andrew Jarombek
# Date: 4/28/2021

apiVersion: v1
kind: Pod
metadata:
  name: saints-xctf-web-e2e
  namespace: jenkins
  labels:
    version: v1.0.0
    environment: all
    application: saints-xctf-web-e2e
spec:
  containers:
    - name: auth
      image: ajarombek/mock-saints-xctf-auth:latest
      tty: true
    - name: functions
      image: ajarombek/mock-saints-xctf-functions:latest
      tty: true
    - name: database
      image: mysql:5.7
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: saintsxctftest
        - name: MYSQL_DATABASE
          value: saintsxctf
        - name: MYSQL_USER
          value: test
        - name: MYSQL_PASSWORD
          value: test
      tty: true
    - name: mysql-aws
      image: ajarombek/mysql-aws:latest
      tty: true
    - name: api
      image: python:3.8
      tty: true
    - name: web
      image: node:14.4.0
      tty: true
    - name: cypress
      image: cypress/included:7.2.0
      tty: true
  serviceAccountName: jenkins-kubernetes-test
  automountServiceAccountToken: true
  restartPolicy: Never
