# Pod holding multiple containers for use with the saints-xctf-api-test Jenkins job.
# Author: Andrew Jarombek
# Date: 10/9/2020

apiVersion: v1
kind: Pod
metadata:
  name: saints-xctf-api-test
  namespace: jenkins
  labels:
    version: v1.0.0
    environment: development
    application: saints-xctf-api-test
spec:
  containers:
    - name: auth
      image: ajarombek/pipenv-flask
      tty: true
    - name: database
      image: mysql:5.7
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: saintsxctftest
      tty: true
    - name: mysql-aws
      image: ajarombek/mysql-aws
      tty: true
    - name: test
      image: python:3.8
      tty: true
