# Pod holding a container for use with the global-kubernetes-infrastructure-test Jenkins job.
# Author: Andrew Jarombek
# Date: 7/6/2020

apiVersion: v1
kind: Pod
metadata:
  name: global-kubernetes-infrastructure-test
  namespace: jenkins
  labels:
    version: v1.0.0
    environment: development
    application: global-kubernetes-infrastructure-test
spec:
  containers:
    - name: go
      image: golang:1.14.4-buster
      tty: true
  serviceAccountName: jenkins-kubernetes-test
  automountServiceAccountToken: true
