# Pod holding containers for use with the destroy-lambda Jenkins job.
# Author: Andrew Jarombek
# Date: 7/19/2021

apiVersion: v1
kind: Pod
metadata:
  name: global-aws-destroy-lambda
  namespace: jenkins
  labels:
    version: v1.0.0
    environment: development
    application: global-aws-destroy-lambda
spec:
  containers:
    - name: terraform
      image: hashicorp/terraform:1.0.1
      command: ["sleep", "infinity"]
      tty: true