# Pod holding a container which connects to MySQL.  Used by the database-script-deployment Jenkins job.
# Author: Andrew Jarombek
# Date: 9/13/2020

apiVersion: v1
kind: Pod
metadata:
  name: database-script-deployment
  namespace: jenkins
  labels:
    version: v1.0.0
    environment: development
    application: saints-xctf-database
spec:
  containers:
    - name: mysql-client
      image: arey/mysql-client:latest
      command: ["sleep", "infinity"]
      tty: true
