# Pod holding multiple containers for use with the graphql-react-prototype-test Jenkins job.
# Author: Andrew Jarombek
# Date: 7/4/2020

apiVersion: v1
kind: Pod
metadata:
  name: graphql-react-prototype-test
  namespace: jenkins
  labels:
    version: v1.0.0
    environment: development
    application: graphql-react-prototype-test
spec:
  containers:
    - name: test
      image: 739088120071.dkr.ecr.us-east-1.amazonaws.com/graphql-react-prototype-base:latest
      tty: true
  restartPolicy: Never
