# Pod holding containers for use with the destroy-s3 Jenkins job.
# Author: Andrew Jarombek
# Date: 7/22/2021

apiVersion: v1
kind: Pod
metadata:
  name: global-aws-destroy-s3
  namespace: jenkins
  labels:
    version: v1.0.0
    environment: development
    application: global-aws-destroy-s3
spec:
  containers:
    - name: terraform
      image: hashicorp/terraform:1.0.1
      command: ["sleep", "infinity"]
      tty: true