# Pod holding multiple containers for use with the test-client Jenkins job.
# Author: Andrew Jarombek
# Date: 4/8/2021

apiVersion: v1
kind: Pod
metadata:
  name: apollo-client-server-prototype-test-client
  namespace: jenkins
  labels:
    version: v1.0.0
    environment: development
    application: apollo-client-server-prototype-test-client
spec:
  containers:
    - name: apollo-client
      image: ajarombek/apollo-client-server-prototype-web:latest
      tty: true
    - name: apollo-server
      image: ajarombek/apollo-client-server-prototype-api:latest
      tty: true
    - name: database
      image: ajarombek/apollo-client-server-prototype-database:latest
      tty: true
    - name: nodejs
      image: node:14.16
      tty: true
    - name: cypress
      image: cypress/included:7.0.1
      tty: true
